// This code was automatically generated by the Crypto CodeGen Haskell utility

func prune1() {
  
}

func prune2() {
  
}

func prune3(unused2 *int) {
  unused1 := 5
  unused2 := unused1
}

func schedule1() {
  o1 := v1 * v2
  o3 := v1 * v3
  o5 := v1 * v4
  o5 := v1 * v1
  o4 := v4 * v4
  o2 := v2 * v3
}
